spring:
  datasource:
      url: jdbc:mysql://localhost:3311/dbkeops?useSSL=false&createDatabaseIfNotExist=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
      show_sql: true
      hbm2ddl: update
      auto: update
server:
   port: 8080   
application:
     name: keops   